CREATE DATABASE IF NOT EXISTS airbnb;

CREATE EXTERNAL TABLE IF NOT EXISTS airbnb.listings_clean (
  listing_id STRING,
  listing_url STRING,
  name STRING,
  summary STRING,
  description STRING,
  property_type STRING,
  room_type STRING,
  bed_type STRING,
  minimum_nights INT,
  maximum_nights INT,
  accommodates INT,
  bedrooms DOUBLE,
  bathrooms DOUBLE,
  beds DOUBLE,
  price DOUBLE,
  weekly_price DOUBLE,
  monthly_price DOUBLE,
  security_deposit DOUBLE,
  cleaning_fee DOUBLE,
  extra_people DOUBLE,
  guests_included INT,
  number_of_reviews INT,
  first_review DATE,
  last_review DATE,
  last_scraped DATE,
  calendar_last_scraped DATE,
  cancellation_policy STRING,
  amenities_csv STRING,
  host_id STRING,
  host_name STRING,
  host_location STRING,
  host_response_time STRING,
  host_response_rate DOUBLE,
  host_is_superhost BOOLEAN,
  host_listings_count INT,
  host_total_listings_count INT,
  host_neighbourhood STRING,
  host_has_profile_pic BOOLEAN,
  host_identity_verified BOOLEAN,
  street STRING,
  suburb STRING,
  government_area STRING,
  market STRING,
  country STRING,
  latitude DOUBLE,
  longitude DOUBLE,
  is_location_exact BOOLEAN,
  review_scores_accuracy INT,
  review_scores_cleanliness INT,
  review_scores_checkin INT,
  review_scores_communication INT,
  review_scores_location INT,
  review_scores_value INT,
  review_scores_rating INT,
  availability_30 INT,
  availability_60 INT,
  availability_90 INT,
  availability_365 INT,
  reviews_count INT,
  ingested_at TIMESTAMP
)
PARTITIONED BY (country_code STRING)
STORED AS PARQUET
LOCATION '/data/airbnb/clean/listings';

MSCK REPAIR TABLE airbnb.listings_clean;
